### ISSUE TITLE
Replace all `raw_input` with `input` from `six` in python3

### ISSUE THREAD

**Issue by prbsparx** [jssimporter/python-jss#101]
Add:
`from six.moves import input`
Then replace all `raw_input` with `input`

Enables jss to configure itself when using python3.

Again... will submit a pull request for this one.

**Comment by nicolas-b12** [comment]
Hey, I have the same issue here. Do you plan to do a PR @prbsparx ? If you don't have time right now, I can take care of this.

**Comment by prbsparx** [comment]
I probably won’t have time for a couple weeks. Just make sure to check all files.

**Comment by grahampugh** [comment]
Solved by #103
