### ISSUE TITLE
Don't read upload file before passing to requests

### ISSUE THREAD

**Issue by moorereason** [jssimporter/python-jss#106]
While attempting to upload a package greater than 2GB to jamf with `JSSImporter` (via [a dataJAR recipe](https://github.com/autopkg/dataJAR-recipes/tree/master/Adobe%202021)), the following error is returned:

```
JSSImporter: Error: string longer than 2147483647 bytes
```

The fix (detailed in https://github.com/psf/requests/issues/2717#issuecomment-130343655) is to pass the file handle to requests and let requests handle the read operations.

I'm not very familiar with `python-jss` (buyer beware!), but changing the following two lines:

https://github.com/jssimporter/python-jss/blob/v2.1.0/jss/distribution_point.py#L661

https://github.com/jssimporter/python-jss/blob/v2.1.0/jss/distribution_point.py#L683

to:
```python
data=resource,
```
resolved the issue for me.

**Comment by grahampugh** [comment]
So you are just changing `data=resource.read(),` to `data=resource,` ?

**Comment by moorereason** [comment]
Correct.  I submitted a PR instead of my rather clumsy bug report.
