### ISSUE TITLE
Search for a computer using MAC address

### ISSUE THREAD

**Issue by gkluoe** [jssimporter/python-jss#67]
I think this is a bug. 

https://github.com/sheagcraig/python-jss/blob/e1982466bd7e971f27525cbc31024590a456df66/jss/jssobjects.py#L186

macadress != macaddress :-)

**Comment by gkluoe** [comment]
In fact it looks like 

`j.Computer('macaddress=xx:xx:xx:xx:xx:xx')`

ought to work, but it doesn't for me (Response Code: 404	Response: Not Found.)

`j.get('/computers/macaddress/xx:xx:xx:xx:xx:xx') `

does work, but returns XML (as expected) rather than a Computer

**Comment by sheagcraig** [comment]
Well, I think they changed the API. I could be wrong, but this definitely used to work.

Looking at the Jamf Pro API docs you have to new endpoints for `/computers/macaddress`, and you have to do `/computers/match/macaddress=...` to do this.

This will have to be updated.

**Comment by gkluoe** [comment]
Ah, interesting. I actually fixed this in my local copy just by fixing the typo in 'macadress' that I highlighted above. That was a while ago so perhaps the API has changed since then.

**Comment by sheagcraig** [comment]
Oh, maybe it does work still then, even though the docs don't specify. I totally missed the spelling error. I'll fix the spelling at least.

**Comment by mosen** [comment]
Seems to be fixed in testing branch.
