### ISSUE TITLE
sslv3 alert handshake failure with JAMF Pro 10.6

### ISSUE THREAD

**Issue by lfshammu** [jssimporter/python-jss#87]
We just updated our JAMF server to 10.6, and since then I haven't been able to get this library to run

Making the following call:
`jamf_xml = j.MobileDevice().retrieve_all(subset="general&location&mobiledevicegroups")`

And I get the resulting exception: 
`requests.exceptions.SSLError: HTTPSConnectionPool(host='ndh-jss-01.corp.contoso.com', port=8443): Max retries exceeded with url: /JSSResource/mobiledevices (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_read_bytes', 'sslv3 alert handshake failure')],)",),))`

I have tried disabling ssl_verify in the JSS prefs, but the issue persists. Any ideas to further troubleshoot this?

**Comment by danengh** [comment]
I was able to get past this by modifying the ssl_version value in tlsadapter.py (/Library/Python/2.7/site-packages/jss/tlsadapter.py)

old:
ssl_version=ssl.PROTOCOL_TLSv1

new:
ssl_version=ssl.PROTOCOL_TLSv1_2

@sheagcraig

**Comment by gkluoe** [comment]
Thanks for tracking this one down! Fix above worked for me.

**Comment by grahampugh** [comment]
In case it helps anyone else, for me, the following location was the one that fixed it:
* `~/Library/Python/2.7/lib/python/site-packages/jss/tlsadapter.py`

**Comment by grahampugh** [comment]
This is now merged into the master branch
