### ISSUE TITLE
Error when installing using pip

### ISSUE THREAD

**Issue by wvanas94** [jssimporter/python-jss#89]
When trying to install the package with pip, I am getting the following error:

$ pip install python-jss
Collecting python-jss
  Could not find a version that satisfies the requirement python-jss (from versions: )
No matching distribution found for python-jss

Cant seem to figure out why. Also, is this package supported by python3?

**Comment by jerrodmartin** [comment]
Try `pip2 install python-jss`.

At this point it is not supported by Python3.  More discussion about that [here.](https://github.com/jssimporter/python-jss/issues/52)

**Comment by grahampugh** [comment]
The version of python-jss installed by pip is now very old - v.1.5.0 doesn't work without editing the `tls_adapter.py` file to cope with new TLS requirements. 

Not to say that we won't ever update the version installed via pip, but at this point I would recommend installing python-jss by installing the JSSImporter package. If you're planning to use AutoPkg/JSSImporter at all, it saves having two different copies of python-jss on the system, each with their own preferences.

This puts python-jss at `/Library/Application Support/JSSImporter/jss`. If you are using python-jss for purposes other than running JSSImporter, you can add this path to your `PYTHONPATH` in your scripts, e.g.: 

```
sys.path.insert(0, '/Library/Application Support/JSSImporter')
import jss
```

Alternatively, put a symlink from `/Library/Python/2.7/site-packages/`, e.g.:

```
ln -s /Library/Python/2.7/site-packages/jss /Library/Application\ Support/JSSImporter/jss
```

We hope to address any remaining python3 dependencies in the coming months.
