### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by sailedeer** [jssimporter/python-jss#93]
I'm wondering if Python3 compatibility is planned for python-jss. I've been using 2to3 to try and get it running for the sake of testing, but that's not feasible for installation on other machines.

**Comment by grahampugh** [comment]
Absolutely planned. But the work has not yet begun.

**Comment by mosen** [comment]
The biggest issue was that sheagcraig had subclassed etree.ElementTree for the XML objects which worked in 2 but is a really difficult strategy to carry forward into py 3 because etree breaks when subclassed. Basically the approach was proxying method calls to an underlying etree instance

**Comment by grahampugh** [comment]
@sailedeer please test out the 2.1.0-dev branch.

**Comment by sailedeer** [comment]
Will try and take a look some time this week. Thanks for the update.

**Comment by grahampugh** [comment]
Python3 compatibility is now merged into master.
